<?php
/***************************************************************
 *  Copyright notice
 *
 *  (c) 2007-2013 Fabien Udriot <fabien.udriot@ecodev.ch>
 *  All rights reserved
 *
 *  This script is part of the TYPO3 project. The TYPO3 project is
 *  free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation; either version 2 of the License, or
 *  (at your option) any later version.
 *
 *  The GNU General Public License can be found at
 *  http://www.gnu.org/copyleft/gpl.html.
 *
 *  This script is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  This copyright notice MUST APPEAR in all copies of the script!
 ***************************************************************/

/**
 * Search and replace for pattern
 */

class tx_ecopatterns {

	/**
	 * Replaces a string matching a pattern in the generated page content
	 * (e.g. single line comments generated by the auto parser)
	 *
	 * @param	array	array containing certain objects
	 * @param	object	tslib_fe object
	 * @return	void
	 */
	function replacePatterns(&$objArr, $tslib_fe) {

		// read rendered page
		$this->content = & $objArr['pObj']->content;
		$records = $this->getDatabaseConnection()->exec_SELECTgetRows('search_pattern, replace_pattern', 'tx_ecopatterns', 'hidden=0');
		// restrict substitutions to the <body> tag (will change in the future)
		$matches = array();

		/*
		 * true when it is valid html (it contains the tag <body).
		 * In this case, split the content in 2 by removing the <head> section
		 */
		if (strpos($this->content, '<body') != null) {
			$htmlOK = TRUE;
			preg_match('/<body.*?>(.+)<\/body>/is', $this->content, $matches);
			if (isset($matches[1])) {
				$work_on = $matches[1];
			}
		} else {
			$work_on = $this->content;
			$htmlOK = FALSE;
		}

		//replace the found patterns by the new values
		if ($work_on) {
			foreach ($records as $record) {
				$work_on = preg_replace('/' . $record['search_pattern'] . '/', $record['replace_pattern'], $work_on);
			}
		}

		if ($htmlOK) {
			// merge parts and set content
			$this->content = preg_replace('/(<body.*?>)(.+)(<\/body>)/is', '\\1' . $work_on . '\\3', $this->content);
		} else {
			$this->content = $work_on;
		}
	}

	/**
	 * Return a pointer to the database.
	 *
	 * @return \TYPO3\CMS\Core\Database\DatabaseConnection
	 */
	protected function getDatabaseConnection() {
		return $GLOBALS['TYPO3_DB'];
	}

}